prefect server start 
  ## => for start prefect server 
prefect project init 
  ## => for deployment
  ## .prefectignore, deployment.yaml, prefect.yaml, .prefect/ will be created.
prefect work-pool create --type process mlops-zoomcamp 
  ## => for create worker
prefect deploy repl.py:main -n nyc_taxi -p mlops-zoomcamp 
  ## => deploy our flow and assign work-pool (mlops-zoomcamp)
prefect worker start -p mlops-zoomcamp -t process
  ## => worker is listening actions
prefect deployment run main/nyc_taxi
  ## => run deployment

## Github (Store) and Docker (Process)
prefect deployment build repl.py:main -n docker-github -q test
  ## => create deployment
prefect deployment apply main-deployment.yaml
  ## => apply deployment
prefect deployment build repl.py:main \
  -n docker-github \
  -q test \
  -sb github/github-storage \
  -ib docker-container/docker-process \
  -o prefect-docker-github-deployment \
  -- apply